version: '3.4'

services:
  data.mirror.in.api:
    image: ei8works/data.mirror.in.api:0.1.1
    build:
      context: .
      dockerfile: ./main/Port.Adapter/In/Api/Dockerfile
  data.mirror.out.api:
    image: ei8works/data.mirror.out.api:0.1.1
    build:
      context: .
      dockerfile: ./main/Port.Adapter/Out/Api/Dockerfile